version: '3'

services:
  node1:
    image: pytorch:1.5.0
    container_name: master_node
    runtime: nvidia  # Укажите, что нужно использовать nvidia runtime
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all  # Укажите количество GPU, которые нужно использовать
    volumes:
      - .:/mnt  # Монтируем текущую директорию в контейнер
    working_dir: /mnt
    # command: /mnt/scripts/entrypoint.sh 1
    networks:
      app_net:
        ipv4_address: 173.17.0.2

  node2:
    image: pytorch:1.5.0
    container_name: slave_node
    runtime: nvidia  # Укажите, что нужно использовать nvidia runtime
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all  # Укажите количество GPU, которые нужно использовать
    volumes:
      - .:/mnt  # Монтируем текущую директорию в контейнер
    # command: /mnt/scripts/entrypoint.sh 2
    networks:
      app_net:
        ipv4_address: 173.17.0.3

networks:
  nn_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 173.17.0.0/16